Change providers strategy
yiisoft/di pull request #143
Opened 2020-09-01 07:25 UTC by yiiliveext

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ✔️

2020-09-03 23:15 UTC, samdark requested changes

2020-09-03 23:15 UTC, samdark commented on src/AbstractContainerConfigurator.php
>  abstract class AbstractContainerConfigurator
Seems it's near to empty now or at least name doesn't reflect the purpose anyway.

2020-09-03 23:15 UTC, samdark commented on src/Container.php
> +        $provider = $this->factory->create($providerDefinition);
Why do we need to create an object right away? Can't we set the config as is?

2020-09-04 06:07 UTC, yiiliveext commented on src/Container.php
> +        $provider = $this->factory->create($providerDefinition);
> Why do we need to create an object right away? Can't we set the config as is?

We need to set params in the provider constructor.

2020-09-04 06:08 UTC, yiiliveext commented on src/Container.php
> +        $provider = $this->factory->create($providerDefinition);
https://github.com/yiisoft/yii-event/blob/master/src/EventDispatcherProvider.php#L24

2020-09-04 13:38 UTC, samdark commented on src/Container.php
> +        $provider = $this->factory->create($providerDefinition);
Discussed in private. Decided that @yiiliveext will adjust it so providers array is returning instances instead of definitions.

2020-09-08 16:11 UTC, BoShurik commented on src/Container.php
>          if ($provider instanceof DeferredServiceProviderInterface) {
Does `DeferredServiceProviderInterface` make sense now? Looks like all providers are lazy now

2020-09-08 22:13 UTC, samdark commented on src/Container.php
>          if ($provider instanceof DeferredServiceProviderInterface) {
@yiiliveext looks like another leftover.

2020-09-09 05:44 UTC, yiiliveext commented on src/Container.php
>          if ($provider instanceof DeferredServiceProviderInterface) {
DeferredProvider is for a heavyweight service initialization. For example, we should make a heavyweight API call and pass the received data to the service constructor. If we use this service only on a few routes, then why do we make the API call on each route? So, we use deferred providers to avoid this.

2020-09-09 06:14 UTC, vjik commented
**Suggestion.**

Add support `\Closure` for providers.
This is can use for not yii-* packages with simple code in providers.

For example, config:

```php
return [
    'yiisoft/csrf' => static function() {
    CsrfToken::initialize();
    return [];
  },
];
```

2020-09-09 07:41 UTC, viktorprogger commented on src/Container.php
> +    private function addProvider($provider): void
```suggestion
    private function addProvider(ServiceProviderInterface $provider): void
```

2020-09-09 09:37 UTC, BoShurik commented on src/Container.php
>          if ($provider instanceof DeferredServiceProviderInterface) {
@yiiliveext 
```php
return [
    HeavyService::class => static function (ContainerInterface $container) {
        $data = $container->get(Api::class)->heavyCall();
        
        return new HeavyService($data);
    },
];
```
Isn't this service will be initialized only when requested?

2020-09-09 10:31 UTC, yiiliveext commented on src/Container.php
>          if ($provider instanceof DeferredServiceProviderInterface) {
> Isn't this service will be initialized only when requested?

Yes, this is another way, it is appropriate in a simple case, but we may have something like that
```php
class Provider implements ServiceProviderInterface
{
     public function getDefinitions(): array
     {
           $rawData = file_get_contents('http:\\mysyte.com\something');
           $dataForFirstService = $this->calculateDataForFirstService($rawData); 
           $dataForSecondService = $this->calculateDataForSecondService($rawData); 
           $dataForThirdService = $this->calculateDataForThirdService($rawData); 

           return [
               FirstService::class => [
                   '__construct()' => [$dataForFirstService],
               ],
               SecondService::class => [
                   '__construct()' => [$dataForSecondService],
               ],
               ThirdService::class => [
                   '__construct()' => [$dataForThirdService],
               ], 
           ]; 
     }

     public function calculateDataForFirstService($data)
     {
          //calculation
     }

     public function calculateDataForSecondService($data)
     {
          //calculation
     }

     public function calculateDataForThirdService($data)
     {
          //calculation
     }     
}
```

2020-09-09 10:56 UTC, BoShurik commented on src/Container.php
>          if ($provider instanceof DeferredServiceProviderInterface) {
@yiiliveext make sense, but can be defined with factories:
```php
return [
    Api::class => [],
    ApiInterface::class => static function (ContainerInterface $container) {
        // To cache requests
        return new CachedApiDecorator($container->get(Api::class));
    },
    ServiceFactory::class => [
        // Also request may be cached in factory
        '__construct' => [Reference::to(ApiInterface::class)],
    ],
    FirstService::class => static function (ContainerInterface $container) {
        return $container->get(ServiceFactory::class)->createFirst();
    },
    SecondService::class => static function (ContainerInterface $container) {
        return $container->get(ServiceFactory::class)->createSecond();
    },
    ThirdService::class => static function (ContainerInterface $container) {
        return $container->get(ServiceFactory::class)->createThird();
    },
];
```

Anyway, in advanced cases you probably need additional data from container to access `API` (tokens, request signer etc)

2020-09-09 11:13 UTC, yiiliveext commented on src/Container.php
>          if ($provider instanceof DeferredServiceProviderInterface) {
> Anyway, in advanced cases you probably need additional data from container to access `API` (tokens, request signer etc)

Yes, I think it would be fine to add `setContainer()` method to `DeferredProviderInterface`.

2020-09-21 11:14 UTC, samdark commented
1. Need to try that on yii-demo and packages. @yiiliveext will do it.
2. Need to decide if that's a good way to go overall.

2020-10-18 22:30 UTC, samdark commented
@yiiliveext seems https://github.com/yiisoft/widget/issues/12 will be broken after the change. How would solve it?

2020-10-19 13:06 UTC, yiiliveext commented
> @yiiliveext seems [yiisoft/widget#12](https://github.com/yiisoft/widget/issues/12) will be broken after the change. How would solve it?

Maybe it is BootstrapMiddleware in the main pipeline?

2020-10-19 22:59 UTC, samdark commented
Yeah, that could be solved that way.

2020-10-24 14:33 UTC, samdark commented
Here's a draft of bootstrapping: https://github.com/yiisoft/app/pull/76

2021-04-20 10:36 UTC, samdark commented
Won't be merged in this variant.

2021-04-20 10:36 UTC, closed without merging