Small refactor, fix tests
yiisoft/di pull request #166
Opened 2020-09-28 17:08 UTC by xepozz

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  |

2020-09-28 17:23 UTC, xepozz commented
Test case is here https://github.com/yiisoft/di/pull/167

2020-09-29 10:09 UTC, samdark commented
@xepozz would you please resolve conflicts?

2020-09-29 10:43 UTC, hiqsol commented
Taken part of this refactoring in https://github.com/yiisoft/di/commit/4042b039f024a384633dac018be7587cead02dd5

2020-10-01 14:49 UTC, samdark requested changes
Seems it does not pass tests.

2020-10-01 14:49 UTC, samdark commented on src/Container.php
> +        $this->set(ContainerInterface::class, $this->rootContainer ?? $this);
Was `has()` check unnecessary? Root container may have it defined.

2020-10-01 14:49 UTC, samdark commented on src/Container.php
> +        $this->set(Injector::class, new Injector($this->rootContainer ?? $this));
Same here. Root container may have it defined.

2020-10-01 14:49 UTC, samdark commented on src/Container.php
> +        if ($container !== $this) {
Can't we simply check for `$this->rootContainer !== null`?

2020-10-01 15:57 UTC, xepozz commented on src/Container.php
> +        $this->set(ContainerInterface::class, $this->rootContainer ?? $this);
> Root container may have it defined

I don't understand you. Can you please explain what do you mean?

2020-10-01 16:01 UTC, xepozz commented on src/Container.php
> +        if ($container !== $this) {
It's not just a check.
It's combine the fix (early fetching container `$this->get(ContainerInterface::class);`) and redefining `Injector` if container definition was modified.

2020-10-02 10:39 UTC, samdark commented on src/Container.php
> +        $this->set(ContainerInterface::class, $this->rootContainer ?? $this);
You have removed a `has()` call. I think it was there to check if there is a definition in a root container already:

```php
$rootContainer = new MyRootContainer();
$rootContainer->define(ContainerInterface::class, function () {
    return new SuperContainer();
});
$yiiContainer = new Container($defintions, $providers, $rootContainer);
```

I am not entirely sure what was the check for. Therefore asking.

2020-10-05 21:23 UTC, samdark commented
The idea was mostly included into other PRs so closing. @xepozz thanks for direction.

2020-10-05 21:23 UTC, closed without merging