New providers
yiisoft/di pull request #233
Opened 2021-08-04 18:33 UTC by yiiliveext

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌

2021-08-04 22:07 UTC, samdark commented on src/Container.php
> +            assert(is_string($provider) || (is_object($provider) && $provider instanceof ServiceProviderInterface),
Moreover, I'm not sure about using `assert()` because it's behavior may be slightly modified by `php.ini` settings: https://www.php.net/manual/en/function.assert.php

2021-08-04 22:07 UTC, samdark commented on src/ExtensibleService.php
> +    public function addExtension(\Closure $closure): void
How to define it?

2021-08-04 22:07 UTC, samdark commented on src/ExtensibleService.php
> +    public function resolve(DependencyResolverInterface $container)
```suggestion
    public function resolve(DependencyResolverInterface $resolver)
```

2021-08-04 22:07 UTC, samdark commented on tests/Unit/ContainerTest.php
> -    public function testNestedContainer(): void
Why was this test removed?

2021-08-04 22:07 UTC, samdark commented on tests/Unit/ContainerTest.php
> -    public function testNestedContainerInProvider(): void
Why was this test removed?

2021-08-04 22:07 UTC, samdark commented on tests/Unit/ContainerTest.php
> +//    public function testCircularReferenceExceptionWhileResolvingProviders(): void
Should pass before merge.

2021-08-05 05:17 UTC, yiiliveext commented on tests/Unit/ContainerTest.php
> +//    public function testCircularReferenceExceptionWhileResolvingProviders(): void
WIP

2021-08-05 05:18 UTC, yiiliveext commented on tests/Unit/ContainerTest.php
> -    public function testNestedContainerInProvider(): void
Because it uses the old internal delegate lookup feature. New we use CompositeContainer to delegate lookup.

2021-08-05 05:23 UTC, yiiliveext commented on src/Contracts/ServiceProviderInterface.php
> +    public function getExtensions(): array;
See this readme https://github.com/container-interop/service-provider/blob/master/README.md
Difference beetween `getDefinitions()` and `getFactories()` is the `getDefinitions()` can returns any definition accepted by the container.

2021-08-05 05:27 UTC, yiiliveext commented on src/CompositeContainer.php
> +                try {
A main feature of the CompositeContainer is the delegate lookup feature, so this is a way to make it for a non-strict container like `yiisoft/di`. I think a non-strict container is a bad idea, because it needs some hacks like this.

2021-08-05 05:29 UTC, yiiliveext commented on src/ExtensibleService.php
> +final class ExtensibleService implements DefinitionInterface
This is a special definition for creating an extensible service. It is used for adding extensions from providers.

2021-08-05 05:30 UTC, yiiliveext commented on src/Container.php
> -    private ?CompositeContainer $rootContainer = null;
We can make a delegate lookup with CompositeContainer now.

2021-08-05 05:34 UTC, yiiliveext commented on src/Container.php
> +        return $definition->resolve(new DependencyResolver($this->get(ContainerInterface::class)));
Yes, this is bad. I think `DependencyResolver` is a bad idea, we should go back to ContainerInterface in the `resolve()` method.

2021-08-05 05:34 UTC, yiiliveext commented on src/Container.php
> +            return $definition->resolve(new DependencyResolver($this->get(ContainerInterface::class)));
See above

2021-08-05 05:36 UTC, yiiliveext commented on src/Container.php
> +        foreach ($extensions as $providerExtensions) {
This allows to extends service many times with different extensions one by one. It works like many decorators.

2021-08-05 05:37 UTC, yiiliveext commented on src/Container.php
> +            assert(is_string($provider) || (is_object($provider) && $provider instanceof ServiceProviderInterface),
This code was here. I just used it in the same manner.

2021-08-05 05:37 UTC, yiiliveext commented on src/ExtensibleService.php
> +    public function addExtension(\Closure $closure): void
See this readme https://github.com/container-interop/service-provider/blob/master/README.md

2021-08-05 05:38 UTC, yiiliveext commented on tests/Unit/ContainerTest.php
> -    public function testNestedContainer(): void
Because it uses the old internal delegate lookup feature. New we use CompositeContainer to delegate lookup.

2021-08-05 07:31 UTC, yiiliveext commented on src/Container.php
> +            return $definition->resolve(new DependencyResolver($this->get(ContainerInterface::class)));
Fixed

2021-08-05 07:31 UTC, yiiliveext commented on src/Container.php
> +        return $definition->resolve(new DependencyResolver($this->get(ContainerInterface::class)));
Fixed

2021-08-05 08:19 UTC, BoShurik commented
Probably I missed something, but at first glance looks like `DeferredServiceProviderInterface:: provides` can be replaced with  `array_keys(ServiceProviderInterface::getDefinitions())`

2021-08-05 08:35 UTC, yiiliveext commented
> Probably I missed something, but at first glance looks like `DeferredServiceProviderInterface:: provides` can be replaced with `array_keys(ServiceProviderInterface::getDefinitions())`
We need separate inteface

2021-08-05 09:01 UTC, yiiliveext commented on src/ExtensibleService.php
> +    public function resolve(DependencyResolverInterface $container)
Fixed

2021-08-05 09:08 UTC, yiiliveext commented on src/Container.php
> +            assert(is_string($provider) || (is_object($provider) && $provider instanceof ServiceProviderInterface),
Fixed

2021-08-05 09:09 UTC, yiiliveext commented on src/Container.php
> +                    throw new InvalidConfigException("Extended service '$id' doesn't exist.");
Fixed

2021-08-05 09:13 UTC, xepozz requested changes

2021-08-05 09:13 UTC, xepozz commented on src/Container.php
> +            foreach ($definitions as $id => $definition) {
Use `setMultiple`

2021-08-05 09:13 UTC, xepozz commented on src/Contracts/ServiceProviderInterface.php
> + *            'car' =>  ['__class' => Car::class],
```suggestion
 *            'car' =>  ['class' => Car::class],
```

2021-08-05 09:13 UTC, xepozz commented on src/ExtensibleService.php
> +            $service = $extension($container, $service);
What about to use `Injector` instead?

2021-08-05 09:13 UTC, xepozz commented on src/Container.php
>                  $this->definitions[$id] = $provider;
It's not related to this PR, but what's the reason do this?

2021-08-05 09:15 UTC, yiiliveext commented on src/ExtensibleService.php
> +            $service = $extension($container, $service);
See this readme https://github.com/container-interop/service-provider/blob/master/README.md

2021-08-05 09:21 UTC, yiiliveext commented on src/CompositeContainer.php
No need

2021-08-05 09:22 UTC, yiiliveext commented on src/CompositeContainer.php
> +                    $firstError = $firstError ?? $e;
Wrong construction https://3v4l.org/8qWi5

2021-08-05 09:24 UTC, yiiliveext commented on src/Container.php
> +            foreach ($definitions as $id => $definition) {
Fixed

2021-08-05 09:24 UTC, yiiliveext commented on src/Container.php
> +            foreach ($definitions as $id => $def) {
Fixed

2021-08-05 09:26 UTC, yiiliveext commented on src/Container.php
>                  $this->definitions[$id] = $provider;
For deferred execution

2021-08-05 09:45 UTC, yiiliveext commented on tests/Unit/ContainerTest.php
> +//    public function testCircularReferenceExceptionWhileResolvingProviders(): void
Done

2021-08-05 13:11 UTC, yiiliveext commented on src/Contracts/ServiceProviderInterface.php
> + *            'car' =>  ['__class' => Car::class],
Fixed

2021-08-05 13:30 UTC, rustamwin commented on src/Container.php
> +        $this->dependencyResolver = $this->dependencyResolver ?? new DependencyResolver($this->get(ContainerInterface::class));
```suggestion
        $this->dependencyResolver ??= new DependencyResolver($this->get(ContainerInterface::class));
```

2021-08-05 13:30 UTC, rustamwin commented on src/Container.php
> +            $this->dependencyResolver = $this->dependencyResolver ?? new DependencyResolver($this->get(ContainerInterface::class));
```suggestion
            $this->dependencyResolver ??= new DependencyResolver($this->get(ContainerInterface::class));
```

2021-08-05 18:18 UTC, xepozz commented on src/CompositeContainer.php
> +                    $firstError = $firstError ?? $e;
It supports with 7.4 and above.

2021-08-05 20:32 UTC, samdark commented on src/CompositeContainer.php
> +                try {
We need to check how making a container strict would affect our configs then.

2021-08-05 20:33 UTC, samdark commented on src/ExtensibleService.php
> +final class ExtensibleService implements DefinitionInterface
Any example?

2021-08-05 20:33 UTC, samdark commented on src/Container.php
> -    private ?CompositeContainer $rootContainer = null;
We need it documented.

2021-08-05 20:35 UTC, samdark commented on src/ExtensibleService.php
> +    public function addExtension(\Closure $closure): void
Need phpdoc.

2021-08-05 21:50 UTC, samdark commented on src/ExtensibleService.php
> +final class ExtensibleService implements DefinitionInterface
How about renaming it to `ServiceExtension`?

2021-08-05 22:21 UTC, samdark commented on src/ExtensibleService.php
> +    public function addExtension(\Closure $closure): void
What do you think about making it a `callable`?

```suggestion
    public function addExtension(callable $closure): void
```

2021-08-06 07:36 UTC, yiiliveext commented on src/Container.php
> +        $this->addProviders($providers);
This is a wrong order. We must register container definitions first, then provider definitions, and then extensions.

2021-08-06 07:42 UTC, BoShurik commented on src/Container.php
> +        $this->addProviders($providers);
What the point? It's definitions, so if there is no identical service names the result will be the same. Isn't it?

2021-08-06 15:40 UTC, samdark commented on src/Container.php
> +        $this->addProviders($providers);
Nope. Provider extensions require services to be already registered by the point they're executed.

2021-08-06 15:48 UTC, BoShurik commented on src/Container.php
> +        $this->addProviders($providers);
What about this?
```php
$this->addProviders($providers);
$this->setMultiple($definitions);
$this->addProvidersExtensions($providers);
```

2021-08-06 15:52 UTC, BoShurik commented on src/Container.php
> +                    throw new InvalidConfigException("Extended service \"$id\" doesn't exist.");
https://github.com/container-interop/service-provider/blob/master/README.md#entry-extension

In the example there is no exception for not defined service and null passed to a callback

2021-08-06 15:54 UTC, samdark approved these changes

2021-08-06 15:55 UTC, samdark commented on src/Container.php
> +                    throw new InvalidConfigException("Extended service \"$id\" doesn't exist.");
Yes. That's difference between container-interop and our own implementation.

2021-08-06 16:42 UTC, merged

2021-08-06 16:42 UTC, samdark commented
Awesome! 👍