Fix has() method
yiisoft/di pull request #240
Opened 2021-08-08 17:56 UTC by yiiliveext

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ✔️

2021-08-09 15:05 UTC, vjik commented on src/Container.php
> +                        $isUnionTypeResolvable = $this->isResolvable($typeName);
Here need break if `$typeName` is resolvable and also need test.

For example: `string|ResolvableObject|NotResolvableObject`. On current code `$isResolvalbe` will be `false`, but should be `true`.

2021-08-09 15:16 UTC, yiiliveext commented on src/Container.php
> +                        $isUnionTypeResolvable = $this->isResolvable($typeName);
On current code `$isResolvable` will be `true`. See tests

2021-08-09 15:17 UTC, yiiliveext commented on src/Container.php
> +                        $isUnionTypeResolvable = $this->isResolvable($typeName);
But this idea with break is good.

2021-08-09 18:10 UTC, xepozz requested changes

2021-08-09 18:10 UTC, xepozz commented on src/Container.php
> +    private function isResolvable($id): bool
```suggestion
    private function isResolvable(string $id): bool
```

2021-08-09 18:10 UTC, xepozz commented on src/Container.php
> +                implode(',', array_keys($this->building['class_exists']))
```suggestion
                implode(', ', array_keys($this->building['class_exists']))
```

2021-08-09 18:10 UTC, xepozz commented on src/Container.php
> +        unset($this->building['class_exists'][$id]);
What about to make a constant for `class_exists`?

2021-08-09 18:10 UTC, xepozz commented on src/Container.php
> +        try {
What about to try to call factory with "SimpleDefinition($class)" instead of duplicating the logic?

2021-08-09 18:10 UTC, xepozz commented on tests/Support/EngineStorage.php
> + */
```suggestion
```

2021-08-09 18:10 UTC, xepozz commented on tests/Support/EngineStorage.php
> +class EngineStorage
```suggestion
final class EngineStorage
```

2021-08-09 18:10 UTC, xepozz commented on tests/Support/EngineStorage.php
> +    public function __construct(EngineInterface $engines)
```suggestion
    public function __construct(EngineInterface $engine)
```

2021-08-09 18:10 UTC, xepozz commented on tests/Support/EngineStorage.php
> +    public function getEngines(): EngineInterface
```suggestion
    public function getEngine(): EngineInterface
```

2021-08-09 18:10 UTC, xepozz commented on tests/Support/UnionTypeInConstructorFirst.php
> +class UnionTypeInConstructorFirst
```suggestion
final class UnionTypeInConstructorFirst
```

2021-08-09 18:10 UTC, xepozz commented on tests/Support/UnionTypeInConstructorFour.php
> +class UnionTypeInConstructorFour
```suggestion
final class UnionTypeInConstructorFour
```

2021-08-09 18:10 UTC, xepozz commented on tests/Support/UnionTypeInConstructorSecond.php
> +class UnionTypeInConstructorSecond
```suggestion
final class UnionTypeInConstructorSecond
```

2021-08-09 18:10 UTC, xepozz commented on tests/Support/UnionTypeInConstructorThree.php
> +class UnionTypeInConstructorThree
```suggestion
final class UnionTypeInConstructorThree
```

2021-08-09 18:11 UTC, xepozz commented
We need to group some test cases in data providers. I will make an issue after this pr will be closed.

2021-08-09 19:04 UTC, yiiliveext commented on src/Container.php
> +        unset($this->building['class_exists'][$id]);
Because building is used too by `buildInternal`

2021-08-09 19:05 UTC, yiiliveext commented on src/Container.php
> +        try {
Because it instantiate services.

2021-08-09 19:20 UTC, vjik commented on src/Container.php
> +                continue;
Why? Seems, break is fine.

Variadic always last argument.
After optional argument always optional or variadic.

2021-08-09 19:25 UTC, BoShurik commented on src/Container.php
> +                continue;
https://3v4l.org/QVR8U

2021-08-09 19:26 UTC, yiiliveext commented on src/Container.php
> +    private function isResolvable($id): bool
has method doesn't have type

2021-08-09 19:27 UTC, yiiliveext commented on src/Container.php
> +                continue;
Ok

2021-08-09 19:48 UTC, xepozz commented on src/Container.php
> +    private function isResolvable($id): bool
But you declared this type in phpdoc

2021-08-09 19:50 UTC, yiiliveext commented on src/Container.php
> +    private function isResolvable($id): bool
For has() type is declared too

2021-08-09 19:53 UTC, xepozz commented on src/Container.php
> +        unset($this->building['class_exists'][$id]);
I talk about to have `$this->building[self::CLASS_EXISTS]` instead of `$this->building['class_exists']`

2021-08-09 19:54 UTC, vjik commented on src/Container.php
> +    private function isResolvable($id): bool
Has - this is method from interface. We don't add type for compatibility with interface.

2021-08-09 19:55 UTC, xepozz commented on src/Container.php
> +        try {
Anyway it doesn't seem that our container should have this code if we already have `factory` for these purposes.

2021-08-10 05:59 UTC, yiiliveext commented on src/Container.php
> +        unset($this->building['class_exists'][$id]);
I think it would be better to create a separate var like `$this->resolableBuilding`

2021-08-10 06:37 UTC, yiiliveext commented on src/Container.php
> +        try {
If this code is not used by the factory, for what purposes we should move it here?

2021-08-10 08:13 UTC, yiiliveext commented on src/Container.php
> +    private function isResolvable($id): bool
Fixed

2021-08-10 08:33 UTC, yiiliveext commented on src/Container.php
> +        unset($this->building['class_exists'][$id]);
Fixed

2021-08-10 11:31 UTC, yiiliveext commented on src/Container.php
> +        try {
Code is moved to the `DefinitionStorage`. Maybe we move it to the factory in the future.

2021-08-11 09:48 UTC, vjik commented on src/CompositeContainer.php
> +        return gettype($variable);
```suggestion
        return is_object($variable) ? get_class($variable) : gettype($variable);
```

2021-08-11 09:48 UTC, vjik commented on src/Container.php
> +     * @var DefinitionStorage storage of object definitions
Storage of object definitions.

2021-08-11 09:48 UTC, vjik commented on src/Container.php
> +        $this->dependencyResolver = new DependencyResolver($this);
Seem, is unnecessary code

2021-08-11 09:48 UTC, vjik commented on src/DefinitionStorage.php
> +    public function hasDefinition(string $id): bool
For me better name `has()`.

2021-08-11 09:48 UTC, vjik commented on src/DefinitionStorage.php
> +    public function getDefinition(string $id)
For me better name `get()`.

2021-08-11 09:48 UTC, vjik commented on src/DefinitionStorage.php
> +    public function setDefinition(string $id, $definition): void
For me better name `set()`.

2021-08-11 09:49 UTC, vjik commented on src/Container.php
> +     * @var DefinitionStorage storage of object definitions
```suggestion
     * @var DefinitionStorage Sstorage of object definitions.
```

2021-08-11 10:03 UTC, samdark commented on src/Container.php
> +            return $this->definitions->hasDefinition($id);
Also, it seems it will make `get()` less performant as well since we now do reflection and dependencies tree traversal both when resolving a definition and when doing `has()`.

2021-08-11 10:06 UTC, samdark commented on src/DefinitionStorage.php
> +final class DefinitionStorage
```suggestion
/**
 * Stores service definitions and checks if a definition could be instantiated.
 * @internal
 */
final class DefinitionStorage
```

2021-08-11 10:06 UTC, samdark commented on src/DefinitionStorage.php
> +    private array $definitions = [];
```suggestion
    private array $definitions;
```

2021-08-11 10:06 UTC, samdark commented on src/DefinitionStorage.php
> +    public function hasDefinition(string $id): bool
```suggestion
    public function has(string $id): bool
```

2021-08-11 10:06 UTC, samdark commented on src/DefinitionStorage.php
> +    public function getDefinition(string $id)
```suggestion
    public function get(string $id)
```

2021-08-11 10:06 UTC, samdark commented on src/DefinitionStorage.php
> +    public function setDefinition(string $id, $definition): void
```suggestion
    public function set(string $id, $definition): void
```

2021-08-11 10:08 UTC, samdark commented on tests/Support/EngineStorage.php
> +    public function __construct(EngineInterface ...$engines)
Argument contradicts `$engines` property type. Here it is array, in other places it's an interface.

2021-08-11 10:09 UTC, samdark commented on tests/Support/EngineStorage.php
> +    public function __construct(EngineInterface ...$engines)
Since it doesn't result in an error, there may be something wrong with tests.

2021-08-11 10:10 UTC, samdark commented on tests/Support/UnionTypeInConstructorThree.php
> +class UnionTypeInConstructorThree
Is it possible to call it something meaningful instead of "three"?

2021-08-11 10:11 UTC, samdark commented on tests/Support/UnionTypeInConstructorSecond.php
> +class UnionTypeInConstructorSecond
Is it possible to call it something meaningful instead of "second"?

2021-08-11 10:11 UTC, samdark commented on tests/Support/UnionTypeInConstructorFour.php
> +class UnionTypeInConstructorFour
Is it possible to call it something meaningful instead of "four"?

2021-08-11 10:11 UTC, samdark commented on tests/Support/UnionTypeInConstructorFirst.php
> +class UnionTypeInConstructorFirst
Is it possible to call it something meaningful instead of "first"?

2021-08-11 10:12 UTC, samdark commented on tests/Unit/AbstractCompositePsrContainerTest.php
> +        $rootContainer = new Container([
Didn't we eliminate a concept of root container? I'd call a outer composite container a root so this is misleading. How about calling it `$applicationContainer`?

2021-08-11 10:13 UTC, samdark commented on tests/Unit/ContainerTest.php
> +    public function testHasPhp8(string $class): void
```suggestion
    public function testUnionTypes(string $class): void
```

2021-08-11 10:13 UTC, samdark commented on tests/Unit/ContainerTest.php
> +            $this->markTestSkipped();
```suggestion
            $this->markTestSkipped('Union types are not supported before PHP 8');
```

2021-08-11 10:14 UTC, samdark commented on tests/Unit/ContainerTest.php
> +    public function dataHasPhp8(): array
```suggestion
    public function dataUnionTypes(): array
```

2021-08-11 10:14 UTC, samdark commented on tests/Unit/ContainerTest.php
> +    public function testHasExistedClassButNotResolvable(): void
```suggestion
    public function testClassExistsButIsNotResolvable(): void
```

2021-08-11 10:15 UTC, samdark commented on tests/Unit/ContainerTest.php
> +    public function dataHasExistedClassButNotResolvablePhp8(): array
```suggestion
    public function dataClassExistButIsNotResolvableWithUnionTypes(): array
```

2021-08-11 10:15 UTC, samdark commented on tests/Unit/ContainerTest.php
> +    public function testHasExistedClassButNotResolvablePhp8(string $class): void
```suggestion
    public function testClassExistButIsNotResolvableWithUnionTypes(string $class): void
```

2021-08-11 10:15 UTC, samdark commented on tests/Unit/ContainerTest.php
> +            $this->markTestSkipped();
```suggestion
            $this->markTestSkipped('Union types are not supported before PHP 8');
```

2021-08-11 20:33 UTC, yiiliveext commented on tests/Support/EngineStorage.php
> +    public function __construct(EngineInterface ...$engines)
Fixed

2021-08-11 20:33 UTC, yiiliveext commented on tests/Unit/AbstractCompositePsrContainerTest.php
> +        $rootContainer = new Container([
Fixed

2021-08-11 20:33 UTC, yiiliveext commented on tests/Unit/ContainerTest.php
> +    public function testHasPhp8(string $class): void
Fixed

2021-08-11 20:34 UTC, yiiliveext commented on tests/Unit/ContainerTest.php
> +            $this->markTestSkipped();
Fixed

2021-08-11 20:34 UTC, yiiliveext commented on tests/Unit/ContainerTest.php
> +    public function dataHasPhp8(): array
Fixed

2021-08-11 20:34 UTC, yiiliveext commented on tests/Unit/ContainerTest.php
> +    public function testHasExistedClassButNotResolvable(): void
Fixed

2021-08-11 20:34 UTC, yiiliveext commented on tests/Unit/ContainerTest.php
> +    public function dataHasExistedClassButNotResolvablePhp8(): array
Fixed

2021-08-11 20:37 UTC, yiiliveext commented on tests/Unit/ContainerTest.php
> +    public function testHasExistedClassButNotResolvablePhp8(string $class): void
Fixed

2021-08-11 20:37 UTC, yiiliveext commented on tests/Unit/ContainerTest.php
> +            $this->markTestSkipped();
Fixed

2021-08-11 20:41 UTC, yiiliveext commented on src/Container.php
> +    private array $resolvableBuilding = [];
Outdated

2021-08-11 20:51 UTC, yiiliveext commented on src/DefinitionStorage.php
> +final class DefinitionStorage
Fixed

2021-08-11 20:51 UTC, yiiliveext commented on src/DefinitionStorage.php
> +    public function hasDefinition(string $id): bool
Fixed

2021-08-11 20:52 UTC, yiiliveext commented on src/DefinitionStorage.php
> +    public function setDefinition(string $id, $definition): void
Fixed

2021-08-11 20:54 UTC, yiiliveext commented on src/Container.php
> +        $this->dependencyResolver = new DependencyResolver($this);
You are wrong. Without this call we have CircularException

2021-08-11 21:03 UTC, yiiliveext commented on src/CompositeContainer.php
> +        return gettype($variable);
Fixed

2021-08-11 21:03 UTC, yiiliveext commented on src/Container.php
> +            throw new \RuntimeException("Id must be string, {$this->getVariableType($id)} given.");
Fixed

2021-08-11 21:03 UTC, yiiliveext commented on src/Container.php
> +    private array $resolvableBuilding = [];
Fixed

2021-08-11 21:07 UTC, yiiliveext commented on src/DefinitionStorage.php
> +        return $this->definitions[$id];
Fixed

2021-08-11 21:12 UTC, yiiliveext commented on src/Container.php
> +            return $this->definitions->hasDefinition($id);
By the benchmarks, the performance does not drop too much

2021-08-11 21:13 UTC, yiiliveext commented on src/Container.php
> +        $this->dependencyResolver = new DependencyResolver($this->get(ContainerInterface::class));
Without the first call, we will get the `CircularReferenceException`

2021-08-12 06:32 UTC, vjik commented on src/Container.php
> +        $this->dependencyResolver = new DependencyResolver($this->get(ContainerInterface::class));
Why for resolve dependencies should used not current container?

2021-08-15 11:35 UTC, samdark commented on src/Container.php
> +        $this->dependencyResolver = new DependencyResolver($this->get(ContainerInterface::class));
Understanbable why it's like that. @yiiliveext said he'll fix it in subsequent PRs.

2021-08-18 19:35 UTC, yiiliveext commented on tests/Support/UnionTypeInConstructorThree.php
> +class UnionTypeInConstructorThree
Fixed

2021-08-18 19:36 UTC, yiiliveext commented on tests/Support/UnionTypeInConstructorSecond.php
> +class UnionTypeInConstructorSecond
Fixed

2021-08-18 19:36 UTC, yiiliveext commented on tests/Support/UnionTypeInConstructorFour.php
> +class UnionTypeInConstructorFour
Fixed

2021-08-18 19:36 UTC, yiiliveext commented on tests/Support/UnionTypeInConstructorFirst.php
> +class UnionTypeInConstructorFirst
Fixed

2021-08-18 22:16 UTC, samdark approved these changes

2021-08-18 22:17 UTC, merged

2021-08-18 22:17 UTC, samdark commented
👍