Add shortcut for tag reference #333
yiisoft/di pull request #353
Opened 2024-02-13 17:29 UTC by xepozz

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | #333

2024-02-13 18:06 UTC, vjik commented on src/Helpers/TagHelper.php
> -final class TagHelper
Why need to make methods `extractTagFromAlias` and `isTagAlias` public? May be keep this internal helper?

2024-02-13 18:11 UTC, xepozz commented on src/Helpers/TagHelper.php
> -final class TagHelper
Because `tag@` is now backed inside the di repo. It's easy to rename it any time if it's needed.
Users may build their own logic on top of the tags and it's good to provide them an api to check and verify tags.

2024-02-13 18:16 UTC, vjik requested changes
Need to add line to changelog and info about `TagReference` to readme.

2024-02-13 18:16 UTC, vjik commented on tests/Unit/Reference/TagReferenceTest.php
> +    public function testExtractWrongTag(): void
Second expressions don't check. Need split to two tests or use data provider.

2024-02-23 07:13 UTC, samdark approved these changes

2024-02-23 07:23 UTC, merged

2024-02-23 07:23 UTC, samdark commented
👍