Update readme.md and other fixes
yiisoft/di pull request #359
Opened 2024-04-19 14:51 UTC by luizcmarin

"## Further reading
- [Martin Fowler's article](https://martinfowler.com/articles/injection.html)."

change localization to  Documentation section

2024-04-24 19:51 UTC, samdark commented on README.md
>  # Benchmarks
That is for internals.

2024-04-25 16:52 UTC, vjik requested changes

2024-04-25 16:52 UTC, vjik commented on LICENSE.md
> +* Redistributions of source code must retain the above copyright
Align it vertically, like here: https://raw.githubusercontent.com/yiisoft/package-template/master/LICENSE.md

2024-04-25 16:52 UTC, vjik commented on README.md
> +>
```suggestion
```

Not need.

2024-04-25 16:52 UTC, vjik commented on README.md
```suggestion
```

2024-04-25 16:52 UTC, vjik commented on README.md
> +The Yii DI is free software. It is released under the terms of the BSD License.
```suggestion
The Yii Dependency Injection is free software. It is released under the terms of the BSD License.
```

2024-04-25 16:52 UTC, vjik commented on docs/internals.md
> +To run the checker, execute the following command:
```suggestion
[Composer](https://getcomposer.org/) dependencies:
```

2024-04-25 16:52 UTC, vjik commented on docs/internals.md
> +## Rector
```suggestion
## Code style
```

2024-04-26 09:13 UTC, vjik commented on docs/internals.md
Why remove "Code style" and "Dependencies" sections?

2024-04-26 09:16 UTC, luizcmarin commented on docs/internals.md
I couldn't resolve the conflicts I created, so I'm trying to go back in time. I saw that in the original readme.md they are not included. Then I removed it.

2024-04-26 09:23 UTC, luizcmarin commented on docs/internals.md
resolved

2024-04-26 12:10 UTC, vjik commented on README.md
>  # Benchmarks
@luizcmarin Benchmarks for internals

2024-04-26 16:03 UTC, merged