Use static function, inline call
yiisoft/di pull request #364
Opened 2024-06-15 07:51 UTC by samdark

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | -

2024-06-15 08:03 UTC, samdark commented
Before:

```
+------+-------------------------+-----------------------------+-----+------+-------------+-------------+--------------+----------------+
| iter | benchmark               | subject                     | set | revs | mem_peak    | time_avg    | comp_z_value | comp_deviation |
+------+-------------------------+-----------------------------+-----+------+-------------+-------------+--------------+----------------+
| 0    | ContainerBench          | benchConstruct              |     | 1000 | 27,042,480b | 368.005μs   | -0.80σ       | -1.22%         |
| 1    | ContainerBench          | benchConstruct              |     | 1000 | 27,042,480b | 367.810μs   | -0.84σ       | -1.28%         |
| 2    | ContainerBench          | benchConstruct              |     | 1000 | 27,042,480b | 370.206μs   | -0.42σ       | -0.63%         |
| 3    | ContainerBench          | benchConstruct              |     | 1000 | 27,042,480b | 383.077μs   | +1.85σ       | +2.82%         |
| 4    | ContainerBench          | benchConstruct              |     | 1000 | 27,042,480b | 373.738μs   | +0.21σ       | +0.31%         |
| 0    | ContainerBench          | benchSequentialLookups      | 0   | 1000 | 39,042,672b | 731.166μs   | -1.93σ       | -2.12%         |
| 1    | ContainerBench          | benchSequentialLookups      | 0   | 1000 | 39,042,672b | 755.112μs   | +0.98σ       | +1.08%         |
| 2    | ContainerBench          | benchSequentialLookups      | 0   | 1000 | 39,042,672b | 749.724μs   | +0.33σ       | +0.36%         |
| 3    | ContainerBench          | benchSequentialLookups      | 0   | 1000 | 39,042,672b | 748.986μs   | +0.24σ       | +0.26%         |
| 4    | ContainerBench          | benchSequentialLookups      | 0   | 1000 | 39,042,672b | 750.180μs   | +0.38σ       | +0.42%         |
| 0    | ContainerBench          | benchSequentialLookups      | 1   | 1000 | 39,207,248b | 773.143μs   | -0.82σ       | -1.31%         |
| 1    | ContainerBench          | benchSequentialLookups      | 1   | 1000 | 39,207,248b | 788.938μs   | +0.45σ       | +0.71%         |
| 2    | ContainerBench          | benchSequentialLookups      | 1   | 1000 | 39,207,248b | 772.115μs   | -0.90σ       | -1.44%         |
| 3    | ContainerBench          | benchSequentialLookups      | 1   | 1000 | 39,207,248b | 777.364μs   | -0.48σ       | -0.77%         |
| 4    | ContainerBench          | benchSequentialLookups      | 1   | 1000 | 39,207,248b | 805.315μs   | +1.76σ       | +2.80%         |
| 0    | ContainerBench          | benchSequentialLookups      | 2   | 1000 | 39,206,968b | 784.482μs   | -0.11σ       | -0.17%         |
| 1    | ContainerBench          | benchSequentialLookups      | 2   | 1000 | 39,206,968b | 777.825μs   | -0.64σ       | -1.02%         |
| 2    | ContainerBench          | benchSequentialLookups      | 2   | 1000 | 39,206,968b | 771.634μs   | -1.14σ       | -1.81%         |
| 3    | ContainerBench          | benchSequentialLookups      | 2   | 1000 | 39,206,968b | 786.878μs   | +0.08σ       | +0.13%         |
| 4    | ContainerBench          | benchSequentialLookups      | 2   | 1000 | 39,206,968b | 808.348μs   | +1.81σ       | +2.87%         |
| 0    | ContainerBench          | benchRandomLookups          | 0   | 1000 | 39,042,672b | 740.180μs   | -0.97σ       | -1.76%         |
| 1    | ContainerBench          | benchRandomLookups          | 0   | 1000 | 39,042,672b | 772.406μs   | +1.39σ       | +2.52%         |
| 2    | ContainerBench          | benchRandomLookups          | 0   | 1000 | 39,042,672b | 760.158μs   | +0.49σ       | +0.89%         |
| 3    | ContainerBench          | benchRandomLookups          | 0   | 1000 | 39,042,672b | 735.636μs   | -1.31σ       | -2.36%         |
| 4    | ContainerBench          | benchRandomLookups          | 0   | 1000 | 39,042,672b | 758.819μs   | +0.40σ       | +0.71%         |
| 0    | ContainerBench          | benchRandomLookups          | 1   | 1000 | 39,207,248b | 806.514μs   | +1.89σ       | +2.71%         |
| 1    | ContainerBench          | benchRandomLookups          | 1   | 1000 | 39,207,248b | 774.862μs   | -0.92σ       | -1.32%         |
| 2    | ContainerBench          | benchRandomLookups          | 1   | 1000 | 39,207,248b | 785.374μs   | +0.01σ       | +0.02%         |
| 3    | ContainerBench          | benchRandomLookups          | 1   | 1000 | 39,207,248b | 782.542μs   | -0.24σ       | -0.35%         |
| 4    | ContainerBench          | benchRandomLookups          | 1   | 1000 | 39,207,248b | 776.978μs   | -0.73σ       | -1.05%         |
| 0    | ContainerBench          | benchRandomLookups          | 2   | 1000 | 39,206,968b | 781.610μs   | -0.35σ       | -0.26%         |
| 1    | ContainerBench          | benchRandomLookups          | 2   | 1000 | 39,206,968b | 776.157μs   | -1.26σ       | -0.96%         |
| 2    | ContainerBench          | benchRandomLookups          | 2   | 1000 | 39,206,968b | 788.666μs   | +0.84σ       | +0.64%         |
| 3    | ContainerBench          | benchRandomLookups          | 2   | 1000 | 39,206,968b | 792.270μs   | +1.45σ       | +1.10%         |
| 4    | ContainerBench          | benchRandomLookups          | 2   | 1000 | 39,206,968b | 779.608μs   | -0.68σ       | -0.52%         |
| 0    | ContainerBench          | benchRandomLookupsComposite | 0   | 1000 | 27,148,232b | 2,208.161μs | -0.94σ       | -1.21%         |
| 1    | ContainerBench          | benchRandomLookupsComposite | 0   | 1000 | 27,148,232b | 2,236.624μs | +0.05σ       | +0.06%         |
| 2    | ContainerBench          | benchRandomLookupsComposite | 0   | 1000 | 27,148,232b | 2,235.382μs | +0.01σ       | +0.01%         |
| 3    | ContainerBench          | benchRandomLookupsComposite | 0   | 1000 | 27,148,232b | 2,287.460μs | +1.81σ       | +2.34%         |
| 4    | ContainerBench          | benchRandomLookupsComposite | 0   | 1000 | 27,148,232b | 2,208.425μs | -0.93σ       | -1.20%         |
| 0    | ContainerBench          | benchRandomLookupsComposite | 1   | 1000 | 27,177,064b | 2,254.359μs | +0.85σ       | +0.71%         |
| 1    | ContainerBench          | benchRandomLookupsComposite | 1   | 1000 | 27,177,064b | 2,218.899μs | -1.05σ       | -0.88%         |
| 2    | ContainerBench          | benchRandomLookupsComposite | 1   | 1000 | 27,177,064b | 2,221.624μs | -0.90σ       | -0.75%         |
| 3    | ContainerBench          | benchRandomLookupsComposite | 1   | 1000 | 27,177,064b | 2,231.336μs | -0.38σ       | -0.32%         |
| 4    | ContainerBench          | benchRandomLookupsComposite | 1   | 1000 | 27,177,064b | 2,266.369μs | +1.49σ       | +1.24%         |
| 0    | ContainerBench          | benchRandomLookupsComposite | 2   | 1000 | 27,176,784b | 2,237.949μs | +0.43σ       | +0.35%         |
| 1    | ContainerBench          | benchRandomLookupsComposite | 2   | 1000 | 27,176,784b | 2,212.973μs | -0.96σ       | -0.77%         |
| 2    | ContainerBench          | benchRandomLookupsComposite | 2   | 1000 | 27,176,784b | 2,206.247μs | -1.33σ       | -1.08%         |
| 3    | ContainerBench          | benchRandomLookupsComposite | 2   | 1000 | 27,176,784b | 2,255.299μs | +1.39σ       | +1.12%         |
| 4    | ContainerBench          | benchRandomLookupsComposite | 2   | 1000 | 27,176,784b | 2,238.790μs | +0.47σ       | +0.38%         |
| 0    | ContainerMethodHasBench | benchPredefinedExisting     |     | 1000 | 5,681,592b  | 126.325μs   | -1.57σ       | -0.95%         |
| 1    | ContainerMethodHasBench | benchPredefinedExisting     |     | 1000 | 5,681,592b  | 127.612μs   | +0.09σ       | +0.05%         |
| 2    | ContainerMethodHasBench | benchPredefinedExisting     |     | 1000 | 5,681,592b  | 127.896μs   | +0.46σ       | +0.28%         |
| 3    | ContainerMethodHasBench | benchPredefinedExisting     |     | 1000 | 5,681,592b  | 128.667μs   | +1.46σ       | +0.88%         |
| 4    | ContainerMethodHasBench | benchPredefinedExisting     |     | 1000 | 5,681,592b  | 127.211μs   | -0.43σ       |  [...]

2024-06-15 09:41 UTC, rustamwin approved these changes

2024-06-15 09:42 UTC, xepozz commented on src/Container.php
> +            if (!$this->definitions->has($id)) {
Isn't it better to check two lines above then?

2024-06-15 13:12 UTC, samdark commented on src/Container.php
> +            if (!$this->definitions->has($id)) {
Outside of the try-catch with duplicating unset? No.

2024-06-16 17:27 UTC, vjik requested changes
Revert incorrect rector changes (phpdoc `@params mixed $var ...`)

2024-06-16 21:15 UTC, merged